version: "3.7"

services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
        resources:
            limits:
              cpus: '0.5'
              memory: 4G
            reservations:
              cpus: '0.2'
              memory: 125MB
    ports:
    - "3000:3000"